# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: DevSkim
        uses: microsoft/DevSkim-Action@v1
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: devskim-results.sarif
          
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.registry }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - run: |
          docker build --file './ZoomFileManager/Dockerfile' --build-arg BUILD_ENV=prod --build-arg BUILD_CONFIG=Release -t '${{ secrets.registry }}/zoomfilemanager:latest' -t docker.pkg.github.com/np-at/zoomrecordinghandler/zoomfilemanager:latest ./
          docker push '${{ secrets.registry }}/zoomfilemanager:latest'

      - name: docker login
        uses: docker/login-action@v1.8.0
        with:
          registry: docker.pkg.github.com
          username: np-at
          password: ${{ github.token }}
         
      - name: push to docker packages
        run: docker push docker.pkg.github.com/np-at/zoomrecordinghandler/zoomfilemanager:latest
          
      - name: Container image scan
        uses: Azure/container-scan@v0
        with:
          # Docker image to scan
          image-name: docker.pkg.github.com/np-at/zoomrecordinghandler/zoomfilemanager:latest
          # Minimum severities of vulnerabilities to be displayed (UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL)
          severity-threshold: MEDIUM # optional, default is HIGH
          username: np-at
          # Username to authenticate to the Docker registry
          # Github token
          # token: # default is ${{ github.token }}
          # Add additional checks to ensure the image is secure and follows best practices and CIS standards
          run-quality-checks: true # optional, default is true
      
